# MODULE 6 - Challenge

## PART 3: Create a Travel Itinerary with a Corresponding Map

In [1]:
# 1. "Directions API" has been enabled for my API key from the Google Cloud Platform.

In [126]:
import pandas as pd
import requests
import gmaps
import gmaps.datasets
from config import g_key
import csv

In [56]:
# 3. Import the "WeatherPy_vacation.csv" file from PART 1 as a new DataFrame.

vacation_data_to_load = "challenge_data/WeatherPy_vacation.csv"

vacation_data_df = pd.read_csv(vacation_data_to_load, index_col=0)  # Added "index_col" to remove unnamed column.)

vacation_data_df.head()

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hrs),Snow inches (last 3hrs)
0,Armenokhorion,GR,2020-01-05 21:00:00,40.8026,21.4609,33.80,75,100,10.47,overcast clouds,0.00,0.0
1,Sandwick,GB,2020-01-05 21:00:00,54.5691,-2.8936,46.85,97,100,12.06,overcast clouds,0.00,0.0
2,Fereydun Kenar,IR,2020-01-05 21:00:00,36.6864,52.5225,45.84,92,58,3.49,broken clouds,0.00,0.0
3,Guerrero,AR,2020-01-05 21:00:00,-24.1859,-65.4469,80.56,86,78,1.63,light rain,1.56,0.0
4,Acapulco,MX,2020-01-05 21:00:00,16.8603,-99.8769,83.88,63,80,7.18,broken clouds,0.00,0.0

In [69]:
# 4. From the Vacation_Search_map in PART 2, select 4 cities: Create DataFrames for each & get lat_lng pairs.

selected_city1 = vacation_data_df[(vacation_data_df["City"] == "Guaruja")]
selected_city2 = vacation_data_df[(vacation_data_df["City"] == "Panambi")]
selected_city3 = vacation_data_df[(vacation_data_df["City"] == "Praia")]
selected_city4 = vacation_data_df[(vacation_data_df["City"] == "Rio Negrinho")]

In [70]:
city1_df = pd.DataFrame(selected_city1)

city1_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hrs),Snow inches (last 3hrs)
44,Guaruja,BR,2020-01-05 21:00:00,-23.9931,-46.2564,74.7,85,68,2.62,light rain,0.31,0.0

In [71]:
city2_df = pd.DataFrame(selected_city2)

city2_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hrs),Snow inches (last 3hrs)
72,Panambi,BR,2020-01-05 21:00:00,-28.2899,-53.5019,88.61,52,86,5.86,overcast clouds,0.0,0.0

In [72]:
city3_df = pd.DataFrame(selected_city3)

city3_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hrs),Snow inches (last 3hrs)
79,Praia,BR,2020-01-05 21:00:00,-20.2488,-43.8055,72.52,92,72,4.29,light rain,1.25,0.0

In [73]:
city4_df = pd.DataFrame(selected_city4)

city4_df

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hrs),Snow inches (last 3hrs)
9,Rio Negrinho,BR,2020-01-05 21:00:00,-26.2591,-49.5178,68.52,92,4,5.75,light rain,2.81,0.0

In [121]:
# Generate lat_lng pairs as DataFrame tuples for selected 4 cities using list indexing.

# USING INDEXING:

In [122]:
select_coord_df = pd.DataFrame({"City": ["Guaruja", "Panambi", "Praia", "Rio Negrinho"], 
                             "Lat": [-23.9931, -28.2899, -20.2488, -26.2591],
                             "Lng": [-46.2564, -53.5019, -43.8055, -49.5178]})

In [123]:
select_coord_df

           City      Lat      Lng
0       Guaruja -23.9931 -46.2564
1       Panambi -28.2899 -53.5019
2         Praia -20.2488 -43.8055
3  Rio Negrinho -26.2591 -49.5178

In [132]:
# 5. Selected 'DRIVING' as travel_mode in the directions_layer.
# 6. Take a screenshot of the route & save as "WeatherPy_travel_map.png"
# 7. Create a marker_layer map for the 4 cities.
# 8. Apply pop-up markers with hotel name, city, country, current weather desc, & max temp.
'''NOTE: # 8 is an incorrect request for this map as only city, lat_lng pairs were requested in this file.
         Providing view of markes with that info from the "Vacation_search.ipynb'''

gmaps.configure(api_key=g_key)

info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Latitude</dt><dd>{Lat}</dd>
<dt>Longitude</dt><dd>{Lng}</dd>
</dl>
"""
locations = select_coord_df[["Lat", "Lng"]]

praia = (-20.2488, -43.8055)
guaruja = (-23.9931, -46.2564)
rioNegrinho = (-26.2591, -49.5179)
panambi = (-28.2899, -53.5019)

fig = gmaps.figure()
praia2panambi = gmaps.directions_layer(praia, guaruja, waypoints=[rioNegrinho, panambi], travel_mode='DRIVING')
fig.add_layer(praia2panambi)
fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
# 9. Take a screenshot of the marker_layer map for the route & save as "WeatherPy_travel_map_markers.png.
'''NOTE: # 9 just like # 8 abor is an incorrect request for this map as only city, lat_lng pairs were requested 
         in this file. Providing view of markes with that info from the "Vacation_search.ipynb'''